name: Raito CLI - Azure Active Directory Plugin - Build
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.1

      - name: Test
        run: make test
        env:
          AD_TENANTID: ${{ secrets.ad_tenantid }}
          AD_CLIENTID: ${{ secrets.ad_clientid }}
          AD_SECRET: ${{ secrets.ad_secret }}

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt